### PR TITLE
[mod] Add new instances template: use GitHub forms

### PR DESCRIPTION
**Pull request by dalf**
related to #188

About antibot section:  

image

New fields:
* country (? searx.space detect this field)
* MITM (searx.space can detect some, but the list is not maintained: https://github.com/searxng/searx-space/blob/master/searxstats/data/asn.py )
* source code:
   * `/config` endpoint provides `git_url`
   * in searx, the value comes [`settings.yml`:`brand.git_url`](https://github.com/searx/searx/blob/e88bea53ebf220648685cdb8eff017357728494e/searx/settings.yml#L8), which might be not updated.
   * here this field explicitly ask to provide the URL
   * it is possible to specify the [git_url in instances.yml](https://github.com/searx/searx-instances/blob/fbe5590245ca3118b07423205ed26ab82766db03/searxinstances/instances.yml#L57)

### CODE REVIEW

**Comment by return42** [comment]
Is this template what we can see in your master branch? 

https://github.com/dalf/searx-instances/issues/new?assignees=&labels=instance+add%2Cinstance&template=add-instance.yaml&title=Add+%3Cinstance+url%3E

**Comment by dalf** [comment]
Yes.

**Comment by dalf** [comment]
@return42  I've updated the form.

ping @unixfox : see [the form on dalf/searx-instances](https://github.com/dalf/searx-instances/issues/new?assignees=&labels=instance+add%2Cinstance&template=add-instance.yaml&title=Add+%3Cinstance+url%3E) or the source code here.

**Review by return42 — COMMENTED** [review]
LGTM (see comment) / thanks!

What about a maintenance  .. one big problem of most engine is the maintenance I think, should we add something like: 

grafik

**Comment by unixfox** [comment]
"Man in the Middle" section is not that useful because searx.space already flag the networks that are doing some MITM like cloudflare. This is useful for invidious because there is no such check.

I would suggest to remove this part.

**Comment by return42** [comment]
> I would suggest to remove this part.

it is not in, was just an suggestion of mine .. but you are right, we tag them already : 

grafik

**Comment by unixfox** [comment]
> > I would suggest to remove this part.
> 
> it is not in, was just an suggestion of mine .. but you are right, we tag them already :
> 
> grafik

Hum yes it is in: https://github.com/searx/searx-instances/pull/189/files#diff-e96f9e68cb96cce4c8d0448962f8026d7cfeec7725decd8b74456fa1e004c26eR41

**Comment by return42** [comment]
Argh, sorry I mixed up things .. it is in!

Sorry for the mess ..

**Comment by dalf** [comment]
Removed. 

See [the form on dalf/searx-instances](https://github.com/dalf/searx-instances/issues/new?assignees=&labels=instance+add%2Cinstance&template=add-instance.yaml&title=Add+%3Cinstance+url%3E) or the source code here.

**Comment by unixfox** [comment]
I've added more changes, @dalf feel free to squash all the commits into one (I don't have git cli installed right now).

**Comment by return42** [comment]
What about maintenance .. should we add a section about (see my comment above)?

**Comment by unixfox** [comment]
> What about maintenance .. should we add a section about (see my comment above)?

I'm going to merge this PR but feel free to submit another one for the "maintenance" section.

Ultimately, searx.space could track the uptime of every searx instance and rank them automatically so that we don't stipulate anything about "required" uptime but that's still a lot of work to develop a feature like this.

**Pull request merged**
